### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'datasets\\LINUX\\processed\\LINUX_ged.pt'

### ISSUE THREAD

**Issue by myseverus** [AlbertTan404/NA-GSL#2]
Hello, is this LINUX_ged.pt downloaded in the code? How to solve it, thank you

**Comment by AlbertTan404** [comment]
The datasets should be automatically downloaded during loading GEDDataset. It seems that it's the issue of pyg. You can try a dry run of loading torch_geometric.datasets.GEDDataset.

**Comment by myseverus** [comment]
> 在加载 GEDDataset 期间，应自动下载数据集。似乎是侏儒的问题。您可以尝试试运行加载 torch_geometric.datasets.GEDDataset。

Thank you very much for your answer, the dataset is downloaded automatically, but this file is not in it
FileNotFoundError: [Errno 2] No such file or directory: 'dataset\\raw\\LINUX\\ged.pickle'

**Comment by AlbertTan404** [comment]
could you please paste the whole log of the error?

**Comment by myseverus** [comment]
> could you please paste the whole log of the error?

Traceback (most recent call last):
  File "C:/Users/20825/Desktop/bioinformations/NA-GSL-main/main.py", line 211, in <module>
    trainer = GEDTrainer(args=parsed_args)
  File "C:\Users\20825\Desktop\bioinformations\NA-GSL-main\trainer.py", line 34, in __init__
    self.dataset = GraphSimDataset(args)
  File "C:\Users\20825\Desktop\bioinformations\NA-GSL-main\data.py", line 25, in __init__
    self.process_dataset()
  File "C:\Users\20825\Desktop\bioinformations\NA-GSL-main\data.py", line 32, in process_dataset
    self.training_graphs = GEDDataset(self.args.data_dir + self.args.dataset, self.args.dataset, train=True)
  File "C:\anaconda\envs\bio_info\lib\site-packages\torch_geometric\datasets\ged_dataset.py", line 141, in __init__
    self.ged = torch.load(path)
  File "C:\anaconda\envs\bio_info\lib\site-packages\torch\serialization.py", line 771, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "C:\anaconda\envs\bio_info\lib\site-packages\torch\serialization.py", line 270, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "C:\anaconda\envs\bio_info\lib\site-packages\torch\serialization.py", line 251, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'datasets\\LINUX\\processed\\LINUX_ged.pt'

**Comment by AlbertTan404** [comment]
Hi, I know what's the issue.
There is a bug in the latest version of GEDDataset in pyg (file path mismatching). There is a walk-around to directly arrange the files like this and then run the code.
![image](https://github.com/user-attachments/assets/88516416-29f0-4f2d-b9c2-ce969c0bd159)

**Comment by myseverus** [comment]
> Hi, I know what's the issue. There is a bug in the latest version of GEDDataset in pyg (file path mismatching). There is a walk-around to directly arrange the files like this and then run the code. ![image](https://private-user-images.githubusercontent.com/108717066/356648629-88516416-29f0-4f2d-b9c2-ce969c0bd159.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMyNzI1MzQsIm5iZiI6MTcyMzI3MjIzNCwicGF0aCI6Ii8xMDg3MTcwNjYvMzU2NjQ4NjI5LTg4NTE2NDE2LTI5ZjAtNGYyZC1iOWMyLWNlOTY5YzBiZDE1OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxMFQwNjQzNTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNTdlYjljYmU5YmY0NDA2NmU4N2NkNGQ0MTA5ZjM0ODVkZjNmODE4MDk5N2YyYWNmNjE3NTE0MzhhOGUwYmU4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.K99RxBzxH2uApuCyqXCr2kbXyJxw5TuOXpz04AEfzzQ)

This does not seem to be the problem. The required file in the error report does not exist in the file automatically downloaded by GEDDataset
![image](https://github.com/user-attachments/assets/2055e16a-f567-427d-819f-1786305d5755)
